services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    command: >-
      sh -c "pnpm run db:studio & pnpm exec next dev --hostname 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./web:/app/web
      - ./db:/app/db
      - pnpm-store:/root/.local/share/pnpm/store
      - node-modules:/app/web/node_modules
volumes:
  pnpm-store:
  node-modules:
